# Default values for briscola-serv.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: mcaci/briscola-serv
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.1.8"

podAnnotations: {}

service:
  type: LoadBalancer
  port: 80

nodeSelector: {}

tolerations: []

affinity: {}

# metallb (load balancer)
metallb:
  address-pools:
  - name: default
    protocol: layer2
    addresses:
    - 172.18.255.200-172.18.255.250