# Default values for briscola-serv.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: mcaci/briscola-serv
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "0.1.3"

podAnnotations: {}

service:
  type: LoadBalancer
  port: 80

nodeSelector: {}

tolerations: []

affinity: {}
