// Code generated by protoc-gen-go. DO NOT EDIT.
// source: briscola/pb/count.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PointCountRequest struct {
	CardNumber           []uint32 `protobuf:"varint,1,rep,packed,name=card_number,json=cardNumber,proto3" json:"card_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PointCountRequest) Reset()         { *m = PointCountRequest{} }
func (m *PointCountRequest) String() string { return proto.CompactTextString(m) }
func (*PointCountRequest) ProtoMessage()    {}
func (*PointCountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_436f15982525bbe3, []int{0}
}

func (m *PointCountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PointCountRequest.Unmarshal(m, b)
}
func (m *PointCountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PointCountRequest.Marshal(b, m, deterministic)
}
func (m *PointCountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PointCountRequest.Merge(m, src)
}
func (m *PointCountRequest) XXX_Size() int {
	return xxx_messageInfo_PointCountRequest.Size(m)
}
func (m *PointCountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PointCountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PointCountRequest proto.InternalMessageInfo

func (m *PointCountRequest) GetCardNumber() []uint32 {
	if m != nil {
		return m.CardNumber
	}
	return nil
}

type PointCountResponse struct {
	Count                uint32   `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PointCountResponse) Reset()         { *m = PointCountResponse{} }
func (m *PointCountResponse) String() string { return proto.CompactTextString(m) }
func (*PointCountResponse) ProtoMessage()    {}
func (*PointCountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_436f15982525bbe3, []int{1}
}

func (m *PointCountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PointCountResponse.Unmarshal(m, b)
}
func (m *PointCountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PointCountResponse.Marshal(b, m, deterministic)
}
func (m *PointCountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PointCountResponse.Merge(m, src)
}
func (m *PointCountResponse) XXX_Size() int {
	return xxx_messageInfo_PointCountResponse.Size(m)
}
func (m *PointCountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PointCountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PointCountResponse proto.InternalMessageInfo

func (m *PointCountResponse) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*PointCountRequest)(nil), "pb.PointCountRequest")
	proto.RegisterType((*PointCountResponse)(nil), "pb.PointCountResponse")
}

func init() { proto.RegisterFile("briscola/pb/count.proto", fileDescriptor_436f15982525bbe3) }

var fileDescriptor_436f15982525bbe3 = []byte{
	// 132 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4f, 0x2a, 0xca, 0x2c,
	0x4e, 0xce, 0xcf, 0x49, 0xd4, 0x2f, 0x48, 0xd2, 0x4f, 0xce, 0x2f, 0xcd, 0x2b, 0xd1, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x32, 0xe1, 0x12, 0x0c, 0xc8, 0xcf, 0xcc, 0x2b,
	0x71, 0x06, 0x89, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0xc9, 0x73, 0x71, 0x27, 0x27,
	0x16, 0xa5, 0xc4, 0xe7, 0x95, 0xe6, 0x26, 0xa5, 0x16, 0x49, 0x30, 0x2a, 0x30, 0x6b, 0xf0, 0x06,
	0x71, 0x81, 0x84, 0xfc, 0xc0, 0x22, 0x4a, 0x5a, 0x5c, 0x42, 0xc8, 0xba, 0x8a, 0x0b, 0xf2, 0xf3,
	0x8a, 0x53, 0x85, 0x44, 0xb8, 0x58, 0xc1, 0xc6, 0x4b, 0x30, 0x2a, 0x30, 0x6a, 0xf0, 0x06, 0x41,
	0x38, 0x49, 0x6c, 0x60, 0xcb, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x06, 0xfa, 0x9d, 0xaf,
	0x87, 0x00, 0x00, 0x00,
}
