apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: example-br-serv
  namespace: default
spec:
  addresses:
  - 172.18.255.200-172.18.255.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty-br-serv
  namespace: default