apiVersion: apps/v1
kind: Deployment
metadata:
  name: brsc
spec:
  selector:
    matchLabels:
      app: brsc
  replicas: 2
  template:
    metadata:
      labels:
        app: brsc
    spec:
      containers:
      - name: brsc
        image: mcaci/briscola-serv:0.0.2
        ports:
        - containerPort: 8080
        - containerPort: 8081
---
kind: Service
apiVersion: v1
metadata:
  name: brsc
  labels:
    app: brsc
spec:
  ports:
    - port: 8080
      name: http
      protocol: TCP
      targetPort: 8080
    - port: 8081
      name: grpc
      protocol: TCP
      targetPort: 8081
  type: LoadBalancer
  selector:
    app: brsc
